# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: LocalAnsibleVM

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
/*
- script:
    ansible-playbook create-dir.yml
  displayName: 'Ansible playbook to create directory'
*/

- script:
    ansilble-playbook facts.yml
  displayName: 'Ansible playbook execution started'