---
- name: Create ansible_directory on remote VM
  hosts: localhost
  become: true
  vars:
    target_user: ruser  # change it as per your requirement
    target_group: ruser # variable
    lock_action: unlock   # values "lock" or "unlock"
  tasks:
    - name: Ensure ansible_directory exists under /
      file:
        path: /ansible_directory-1
        state: directory
        mode: '0755'

  tasks:
    - name: to create remoteuser in ansible host
      ansible.builtin.user:
        name: ruser
        comment: "remote user"
        shell: /bin/ksh
        create_home: yes
        state: present
    - name: Unlock .ssh directory if immutable (pre-step)
      command: "chattr -i /home/{{ target_user }}/.ssh"
      ignore_errors: true   # safe if not immutable yet

  tasks:
    - name: ensure the .ssh directory exists
      file:
        path: "/home/{{ target_user }}/.ssh"
        state: directory
        owner: "{{ target_user }}"
        group: "{{ target_group }}"
        mode: '0700'
    - name: lock .ssh directory (immutable)
      command: "chattr +i /home/{{ target_user }}/.ssh"
      when: lock_action == "lock"
    - name: unlock .ssh directory (remove (immutable)
      command: "chattr -i /home/{{ target_user }}/.ssh"
      when: lock_action == "unlock"



    