---
- name: Create ansible_directory on remote VM
  hosts: localhost
  become: true
  tasks:
    - name: Ensure ansible_directory exists under /
      file:
        path: /ansible_directory
        state: directory
        mode: '0755'