version: '3.8'

services:
  nginx-custom:
    image: 1601071/docker-images:latest   # Pulls image from Docker Hub
    container_name: balaji-nginx-19042026
    ports:
      - "8080:80"
    environment:
      - APP_NAME=docker-images
      - PROJECT=app-project
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge