---
- name: Deploy and run var housekeeping script
  hosts: 192.168.0.104
  become: yes

  vars:
    script_src: "https://github.com/balajigvhcl/application/blob/feature-linuxvm-ansible-deploy/scripts/housekeep.sh"
    script_dest: /tmp/housekeep.sh
    action: dryrun   # default (override at runtime)

  tasks:
    - name: Download script from github repoistory
      ansible.builtin.get_url:
        url: "{{ script_url }}"
        dest: "{{ script_dest }}"
        mode: '0755'

    #- name: Copy housekeeping script
    #  ansible.builtin.copy:
    #    src: "{{ script_src }}"
    #    dest: "{{ script_dest }}"
    #    mode: '0755'

    - name: Ensure /var/crash exists
      ansible.builtin.file:
        path: /var/crash
        state: directory
        mode: '0755'

    - name: Run housekeeping script with selected action
      ansible.builtin.command: "{{ script_dest }} {{ action }}"
      register: housekeep_output

    - name: Show output (stdout)
      ansible.builtin.debug:
        var: housekeep_output.stdout_lines

    #- name: Fetch log file from remote
    #  ansible.builtin.fetch:
    #    src: "/tmp/{{ action }}_housekeep.log"
    #    dest: "./logs/{{ inventory_hostname }}_{{ action }}.log"
    #    flat: yes
